---
- debug:
    var: _remote
  when:
    - pantheon_backup.debug | default(false) == true

- name: Rotate files on S3 if a retainCount is set.
  shell: >
    s3cmd mv
    {% if _remote.host is defined %}
    --host={{ _remote.host | quote }}
    {% endif %}
    {% if _remote.hostBucket is defined %}
    --host-bucket={{ _remote.hostBucket | quote }}
    {% endif %}
    --access_key={{ _access_key | quote }}
    --secret_key={{ _secret_key | quote }}
    --acl-private
    s3://{{ _src_path }} s3://{{ _dest_path }}
  loop: "{{ range(((_target.retainCount | default(1)) -2), -1, -1) }}"
  vars:
    _access_key: "\
      {% if _remote.accessKeyFile is defined %}\
      {{ lookup('file', _remote.accessKeyFile) }}\
      {% else %}\
      {{ _remote.accessKey | default(omit) }}\
      {% endif %}"
    _secret_key: "\
      {% if _remote.secretKeyFile is defined %}\
      {{ lookup('file', _remote.secretKeyFile) }}\
      {% else %}\
      {{ _backup.secretKey | default(omit) }}\
      {% endif %}"
    _src_path: "\
      {{ _remote.bucket }}/\
      {% if _target.path is defined %}\
      {{ _target.path }}/\
      {% endif %}\
      {{ _backup_file_prefix }}-{{ item }}.{{ _backup_file_suffix }}"
    _dest_path: "\
      {{ _remote.bucket }}/\
      {% if _target.path is defined %}\
      {{ _target.path }}/\
      {% endif %}\
      {{ _backup_file_prefix }}-{{ item + 1 }}.{{ _backup_file_suffix }}"
  when:
    - _target.retainCount | default(1) > 1
  ignore_errors: true
  no_log: "{{ pantheon_backup.debug | default(false) | ternary(false, true) }}"

- name: Push backup to S3
  shell: >
    s3cmd put
    {% if _remote.host is defined %}
    --host={{ _remote.host | quote }}
    {% endif %}
    {% if _remote.hostBucket is defined %}
    --host-bucket={{ _remote.hostBucket | quote }}
    {% endif %}
    --access_key={{ _access_key | quote }}
    --secret_key={{ _secret_key | quote }}
    --acl-private
    {{ _backup_file_path }} s3://{{ _dest_path }}
  vars:
    _access_key: "\
      {% if _remote.accessKeyFile is defined %}\
      {{ lookup('file', _remote.accessKeyFile) }}\
      {% else %}\
      {{ _remote.accessKey | default(omit) }}\
      {% endif %}"
    _secret_key: "\
      {% if _remote.secretKeyFile is defined %}\
      {{ lookup('file', _remote.secretKeyFile) }}\
      {% else %}\
      {{ _backup.secretKey | default(omit) }}\
      {% endif %}"
    _dest_path: "\
      {{ _remote.bucket }}/\
      {% if _target.path is defined %}\
      {{ _target.path }}/\
      {% endif %}\
      {{ _backup_file_prefix }}-0.{{ _backup_file_suffix }}"
  no_log: "{{ pantheon_backup.debug | default(false) | ternary(false, true) }}"

